version: '3'
services:
  db:
    image: postgres:15.1-alpine
    ports:
      - '5432'
    restart: always
    container_name: ${DB_CONTAINER}
    hostname: ${DB_HOST}
    environment:
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    volumes:
      - ahs-db-data-production:/var/lib/postgresql/data

  webapp:
    image: chriswebdev1/ahs_webapp:production
    container_name: ahs_webapp_production
    restart: always
    hostname: ${APP_HOST}
    ports:
      - '3001:3000'
    environment:
      - 'JWT_HASH=${JWT_HASH}'
      - 'DATABASE_URL=${DATABASE_URL}'
      - 'ORIGIN=${ORIGIN}'

volumes:
  ahs-db-data-production:
