/*
  Warnings:

  - The values [UNCLEAR_SALARY_CALCULATION,CASUAL_OVERTIME] on the enum `RedFlag` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "RedFlag_new" AS ENUM ('UNPAID_INTERNSHIP', 'UNPAID_OVERTIME', 'STARVING_SALARY', 'UNEQUAL_SALARIES', 'CHANGES_IN_EMPLOYMENT_CONDITIONS', 'DELAYED_PAYSLIPS', 'PAYCHECK_LOWER_THEN_AGREED', 'NO_SALARY_INCREASES_OR_BONUSES', 'UNPAID_OR_DEDUCTED_EXPENSES', 'TRASH_CONTRACTS', 'BORING_PROJECTS', 'INSIGNIFICANT_MONOTONOUS_TASKS', 'TASKS_DONT_MATCH_JOB_DESCRIPTION', 'CHEAPEST_SOLUTIONS_AND_BASIC_DESIGN', 'CANT_GET_MEANINGFUL_EXPERIENCE', 'GLASS_CEILING', 'LACK_OF_MENTORING', 'NO_VARIETY_IN_RESPONSIBILITIES', 'NO_PERSONAL_DEVELOPMENT_PLAN_OR_EDUCATION_BUDGET', 'NOT_POSSIBLE_TO_INFLUENCE_COMPANY_STRATEGY', 'MISSING_OR_STUDENTS_LICENSE', 'REQUIRED_PRIVATE_HARDWARE_OR_SOFTWARE', 'OFFBRAND_OR_FREE_SOFTWARE', 'OLD_HARDWARE_OUTDATED_SOFTWARE', 'BAD_WORKSTATION_BAD_OFFICE', 'MISSING_BASIC_OFFICE_SUPPLIES', 'MICROMANAGEMENT', 'INCOMPETENT_MANAGEMENT', 'INABILITY_TO_GET_PROFITABLE_ASSIGNMENTS', 'FINANCIAL_PROBLEMS', 'OVERLY_RELYING_ON_INTERNS_OR_FREE_LABOUR', 'ILLEGAL_OR_IMMORAL', 'TOXIC_ATMOSPHERE', 'FAVORITISM', 'ABUSE_MOBBING', 'STRESS_PRESSURE', 'INCOMPETENT_TEAM', 'UNREALISTIC_DEADLINES', 'SYSTEMATIC_OVERTIME', 'WORK_ON_WEEKEND_AND_HOLIDAYS', 'DENIED_TIME_OFF', 'OVERWHELMING_RESPONSIBILITY', 'ABLEISM', 'AGISM', 'HOMOPHOBIA', 'NEPOTISM', 'RACISM', 'SEXISM', 'TRANSPHOBIA', 'XENOPHOBIA');
ALTER TABLE "RedFlagCounter" ALTER COLUMN "redFlagName" TYPE "RedFlag_new" USING ("redFlagName"::text::"RedFlag_new");
ALTER TABLE "RedFlagSurvey" ALTER COLUMN "redFlags" TYPE "RedFlag_new"[] USING ("redFlags"::text::"RedFlag_new"[]);
ALTER TYPE "RedFlag" RENAME TO "RedFlag_old";
ALTER TYPE "RedFlag_new" RENAME TO "RedFlag";
DROP TYPE "RedFlag_old";
COMMIT;
